---
# ==================================
# App Deploy Role - Handlers
# ==================================

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes

- name: reload httpd
  systemd:
    name: httpd
    state: reloaded

- name: restart application
  systemd:
    name: httpd
    state: restarted
  listen: "restart app"
